// This file is generated by Slice Machine. Update with care!

import GridImage from './GridImage';
import HeroBanner from './HeroBanner';
import RichText from './RichText';
import TextWithImage from './TextWithImage';

export {
	GridImage,
	HeroBanner,
	RichText,
	TextWithImage,
};

export const components = {
	grid_image: GridImage,
	hero_banner: HeroBanner,
	rich_text: RichText,
	text_with_image: TextWithImage,
};
